### ISSUE TITLE
Possible negative values 

### ISSUE THREAD

**Issue by CedricVidrequin** [yonik/java_util#2]
I used this code and I face negative values for the following [key ; seed] pairs : 
[ 0009B5192953 ; 100 ] : return -2042646103
[ 0009B5192987 ; 100 ] : return -743736962

Here is how I use the code : 
int ret4 = MurmurHash3.murmurhash3_x86_32(key, 0, key.length(), 100);

Is it a bug or did I miss something ?

**Comment by DipalPrajapati** [comment]
Hi , I am not able test the speed.

**Comment by yonik** [comment]
The has returns a full 32 bits.  A java 32 bit integer is always signed, hence roughly half of the time it will be a negative integer (if you interpret it as such).  Another way to think about it is that it's just a bit pattern (depending on what you do with it).

If you only want positive 32 bit integers, you can throw away the top sign bit:
  result & 0x7fffffff;

Or, you can move the 32 bits into a 64 bit long (using a mask to avoid sign extension):
int positiveResult = (0x0FFFFFFFFL & result);

**Comment by CedricVidrequin** [comment]
Thank you for the clue !
